- name: "Copy script into Rook tools pod"
  shell: kubectl -n rook-ceph cp {{ path_template_append_force_http }} $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}'):/
  delegate_to: 127.0.0.1
  connection: local

- name: "Excute script copied in Rook tools pod"
  shell: kubectl -n rook-ceph exec  $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') /bin/bash /append_force_http.sh
  delegate_to: 127.0.0.1
  connection: local


- name: "wait for Heimdall to come up"
  uri:
    url: "{{ heimdall_url }}/"
    status_code: 200
    validate_certs: "{{ validate_certs }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- pause:
    prompt: "Create admin with a password"

- name: Transfering template to /tmp
  template: src={{ item }} dest=/tmp/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - templates/heimdall/*.j2

- name: "Install sqlite3 and insert items"
  shell: |
    kubectl --namespace=seedbox exec -it {{ heimdall_pod.stdout }} --  apk --update add sqlite sqlite-dev
    kubectl cp /tmp/items.sql seedbox/{{ heimdall_pod.stdout }}:/tmp/items.sql
    kubectl --namespace=seedbox exec -it {{ heimdall_pod.stdout }} -- bash -c  "sqlite3 /config/www/app.sqlite < /tmp/items.sql"
  args:
    warn: false
